### ISSUE TITLE
qeds.themes.mpl_style()  causes recursion errors in Google Colab

### ISSUE THREAD

**Issue by pjakobsen** [QuantEcon/qeds#3]
```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-8-9bae9beea5a0> in <module>()
      7 # activate plot theme
      8 import qeds
----> 9 qeds.themes.mpl_style();
     10 plotly_template = qeds.themes.plotly_template()
     11 colors = qeds.themes.COLOR_CYCLE

1 frames
... last 1 frames repeated, from the frame below ...

/usr/local/lib/python3.6/dist-packages/qeds/themes.py in mpl_style()
     49     rcp['axes.labelsize'] = 'large'
     50 
---> 51     plt.style.library["qeds"] = mpl_style()
     52     plt.style.reload_library()
     53     plt.style.use("qeds")

RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by pjakobsen** [comment]
I forked, looking through code.  This self referential call inside mpl_style() here is either an oversight, or beyond my comprehension of pythonic best practices.   

` plt.style.library["qeds"] = mpl_style()`

 I will fix it if someone would tell me what the call is supposed to do, and then I can issue a pull request.   Thanks :)

**Comment by wupeifan** [comment]
It turns out that we need to examine more than this function, as I can see several error messages when running codes under `qeds` on Colab. Thanks a lot for looking into this!

**Comment by sglyon** [comment]
This line definitely shouldn't be there. not sure how it wasn't causing problems before 🤷‍♂ 

I'd gladly review a PR that addresses it

**Comment by sglyon** [comment]
I think the fix would be to change that line to

```
plt.style.library["qeds"] = rcp
```

I'd make the change myself, but won't have time in the short run to properly test it and verify that it works

**Comment by jlperla** [comment]
@wupeifan are you able to give it a shot with arnavs help for some testing?

**Comment by wupeifan** [comment]
Sure, I can help with testing myself too.

**Comment by pjakobsen** [comment]
Thanks for the quick response.  I will make the change, test it on various platforms, and issue a pull request.
